### ISSUE TITLE
Why do the same reminders keep getting added to the calendar over and over again every time I open it?

### ISSUE THREAD

**Issue by BingBing160809** [cinaq/reminders2calendar#5] opened 2023-07-25 18:04 UTC
1. Why do the same reminders keep getting added to the calendar over and over again every time you open it?
2. The reminder I put in personal is showing up in school.
![微信图片_20230726020236](https://github.com/cinaq/reminders2calendar/assets/140324875/0ca1ddd9-b228-464a-bb33-6477da98a32a)
![微信图片_20230726020248](https://github.com/cinaq/reminders2calendar/assets/140324875/42739228-8ece-4ca0-892e-d5f8eba08a95)

**Comment by burnzy** [comment] 2023-09-07 16:25
I experienced this as well. The issue is that there is a bug in the two "Add" event actions in the Reminders2Calendar shortcut. Instead of using the "ListName" variable, it is using the first calendar it detects. The fix is to set the "Calendar" value to `ListName`. See screenshot:

<img width="619" alt="Screen Shot 2023-09-07 at 12 21 03" src="https://github.com/cinaq/reminders2calendar/assets/1924452/b037bd0f-873e-497e-b77b-5b1b27b72a52">

Maybe @xiwenc can release a new patch version when he has time. It's a great shortcut by the way, thanks @xiwenc !

**Comment by xiwenc** [comment] 2023-09-07 17:36
Hi,

This is already the case:

<img width="735" alt="image" src="https://github.com/cinaq/reminders2calendar/assets/1109695/312089a9-cc15-4a42-a701-dc298b20a586">

I will re-export my version just in case I forgot to update. 

Please try the latest export and let me know if that works.

**Comment by xiwenc** [comment] 2023-09-07 17:42
I have been using the build of https://github.com/cinaq/reminders2calendar/commit/28bfd8a406394c15127e198fd904d9d00608318c for a while and I don't see duplicates. Hope this solves your problem.

I will close this issue for now. Feel free to re-open if the issue still persists.

**Closed as completed by xiwenc** 2023-09-07 17:42 UTC

**Comment by burnzy** [comment] 2023-09-07 18:24
> Hi,
> 
> This is already the case:
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/1109695/266397533-312089a9-cc15-4a42-a701-dc298b20a586.png">
> 
> I will re-export my version just in case I forgot to update.
> 
> Please try the latest export and let me know if that works.

Strange, just tried your latest release and that one still has the problem — where the Calendar item isn't set to `ListName` but to one of my calendars. Maybe a shortcuts bug then? Not sure

**Comment by xiwenc** [comment] 2023-09-07 19:11
@burnzy sounds weird indeed. I've retested it over and over again. It works fine on my end. My advice is to remove the shortcut and reimport from github again. We have added a Loop helper shortcut now. See the updated README file.

**Comment by xiwenc** [comment] 2023-09-17 20:49
I've found why the duplication sometimes happens. The query to look for next N days does not include "today" events. Therefore it would ignore existing events due "today" and hence creates new event. These result in duplicates.

It's fixed already. Ran into this same edge case in jira2calendar.
